# Generated by Django 6.0.8 on 2026-09-10 05:15

import bakerydemo.videogen.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.WAGTAIL_PAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('narration_script', models.TextField(help_text="The article's own words that are narrated, verbatim.")),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('progress_percentage', models.PositiveSmallIntegerField(default=0)),
                ('workflow_run_id', models.CharField(blank=True, max_length=255)),
                ('project_id', models.CharField(blank=True, max_length=255)),
                ('export_id', models.CharField(blank=True, max_length=255)),
                ('export_file_id', models.CharField(blank=True, max_length=255)),
                ('video_file', models.FileField(blank=True, null=True, upload_to=bakerydemo.videogen.models.video_upload_to)),
                ('error', models.TextField(blank=True)),
                ('error_code', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_job', to=settings.WAGTAIL_PAGE_MODEL)),
            ],
            options={
                'verbose_name': 'video job',
                'ordering': ['-created_at'],
            },
        ),
    ]
