# Generated by Django 6.0.8 on 2026-09-10 06:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.WAGTAIL_PAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress_percentage', models.PositiveSmallIntegerField(default=0)),
                ('script', models.TextField(blank=True, default='')),
                ('error', models.TextField(blank=True, default='')),
                ('workflow_run_id', models.CharField(blank=True, default='', max_length=255)),
                ('project_id', models.CharField(blank=True, default='', max_length=255)),
                ('export_id', models.CharField(blank=True, default='', max_length=255)),
                ('export_file_id', models.CharField(blank=True, default='', max_length=255)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='article_videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='article_video', to=settings.WAGTAIL_PAGE_MODEL)),
            ],
            options={
                'verbose_name': 'article video',
                'verbose_name_plural': 'article videos',
            },
        ),
    ]
