# Generated by Django 6.0.8 on 2026-09-10 06:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.WAGTAIL_PAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='processing', max_length=16)),
                ('progress_percentage', models.PositiveSmallIntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('script', models.TextField(blank=True, default='')),
                ('workflow_run_id', models.CharField(blank=True, default='', max_length=255)),
                ('project_id', models.CharField(blank=True, default='', max_length=255)),
                ('export_id', models.CharField(blank=True, default='', max_length=255)),
                ('download_url', models.TextField(blank=True, default='')),
                ('download_url_signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='article_video', to=settings.WAGTAIL_PAGE_MODEL)),
            ],
            options={
                'verbose_name': 'article video',
                'verbose_name_plural': 'article videos',
                'ordering': ['-created_at'],
            },
        ),
    ]
