# Generated by Django 6.0.8 on 2026-09-09 19:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.WAGTAIL_PAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('progress_percentage', models.PositiveSmallIntegerField(default=0)),
                ('script', models.TextField(blank=True)),
                ('workflow_run_id', models.CharField(blank=True, max_length=255)),
                ('project_id', models.CharField(blank=True, max_length=255)),
                ('export_id', models.CharField(blank=True, max_length=255)),
                ('export_file_id', models.CharField(blank=True, max_length=255)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='article_videos/')),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.OneToOneField(help_text='The article this video was produced from.', on_delete=django.db.models.deletion.CASCADE, related_name='video_job', to=settings.WAGTAIL_PAGE_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
