# Generated by Django 6.0.8 on 2026-09-10 05:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.WAGTAIL_PAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('progress_percentage', models.PositiveSmallIntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('script', models.TextField(blank=True, default='')),
                ('workflow_run_id', models.CharField(blank=True, default='', max_length=128)),
                ('project_id', models.CharField(blank=True, default='', max_length=128)),
                ('export_id', models.CharField(blank=True, default='', max_length=128)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='article_videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_jobs', to=settings.WAGTAIL_PAGE_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'failed'), _negated=True), fields=('page',), name='one_active_video_job_per_page')],
            },
        ),
    ]
